name = "person-tracker-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "46e1e5cbbb675cf9bc2a04283b31c6b7"

[[d1_databases]]
binding = "DB"
database_name = "person-tracker-db"
database_id = "b61adfdb-ca6a-4243-a09c-c15a61a2cb37"
